### ISSUE TITLE
Can't see card number when drawing

### ISSUE THREAD

**Issue by Herr-chirurg** [Maxentr/Skyjo#35]
When a card is selected on a pile, the card go blank instead of showing the card number.
It's the case for the face down pile but also for the face up pile.

**Expected behavior :**

When a card is selected on a pile, the card must show the card number.

**To reproduce :**

Each games i began had this bug

**Screenshots**
![bug](https://github.com/Maxentr/Skyjo/assets/46657618/5377de29-e60b-4d0d-a125-d378513dcfeb)

**Desktop**

- Windows
- Chrome, Mozilla

Additional :
Thanx for the best implementation of skyjo i've found online !
Help when work is boring

**Comment by Maxentr** [comment]
Hello,
It's because the API is not up to date. I've pushed the new version but it doesn't work and I don't know why. I'll have a look at it this evening

**Comment by Maxentr** [comment]
The path to the index.js in the prod script was wrong...
