### ISSUE TITLE
Add a .env.example file and a quick-start guide for setting up the development environment

### ISSUE THREAD

**Issue by GatienFrenchDev** [maxentr/skyjo#82]
**Purpose:**  
To make the installation and configuration process smoother, adding a `.env.example` file with necessary environment variables would be very helpful. This would allow new contributors to easily understand the required variables without guessing.

**Proposed Solution:**
- Create a `.env.example` file that includes all necessary environment variables, even with placeholder or sample values if sensitive.
- Add a quick setup guide in the `README.md` or `CONTRIBUTING.md` to explain how to:
  1. Copy the `.env.example` file to `.env` and fill in the required values.
  2. Install dependencies and launch the project locally.

**Benefits:**
- Makes it easier for new contributors to get started.
- Reduces the risk of configuration errors related to missing or misunderstood environment variables.

Providing clear setup instructions and a sample environment file can greatly improve the developer experience, creating a more accessible and friendly project setup.

**Comment by maxentr** [comment]
Hi @GatienFrenchDev,

I’ve updated the `README.md` to include sections for "Installation guide" and "How to run the project." Additionally, I’ve created a `CONTRIBUTING.md` file to provide guidance for new contributors.

Let me know if these changes work for you or if there’s anything else we could add to make onboarding smoother!
