### ISSUE TITLE
bug view opponents' games on mobiles

### ISSUE THREAD

**Issue by Cosmos506** [maxentr/skyjo#84]
on mobile, we can only see the current player's game and not those of other players, even if we click on their name on the left.

Can you fixed it please ?

CosmosDev

**Comment by maxentr** [comment]
Hi @CosmosDev,

Thank you for reporting this issue! I've identified and resolved the problem and made some improvements to the UI. Could you check if this good for you?

**Comment by Cosmos506** [comment]
I tested it with two of my friends. With three, the problem is still present for 2 of us.
my 1st friend clicks on the players on the left of the screen and everything works he can see their game. but my other friend and I even clicking on the first names of the other players to see their games it does not work. want a picture or it's good ?

**Comment by maxentr** [comment]
I’ve tested the changes locally, and everything works fine on my end.

Could you confirm if you’re experiencing this bug locally as well? If so, could you share the steps or any relevant details to help me reproduce it? That would be very helpful for further investigation.

As for the second change you mentioned, here’s what I’ve tried:

<img width="304" alt="Screenshot 2024-11-26 at 16 10 33" src="https://github.com/user-attachments/assets/d1b9b447-4a24-4d54-849d-8a0c6100b335">
<img width="308" alt="Screenshot 2024-11-26 at 16 09 15" src="https://github.com/user-attachments/assets/f1b29698-209d-450e-b8e0-b8d742d03e39">



Does this align with what you’re looking for?

**Comment by Cosmos506** [comment]
I'm not at home, if I try on the site does it work or do I have to try locally?

**Comment by maxentr** [comment]
As for the bug related to viewing opponents' games on mobile, this has only been fixed locally (not on [skyjo.online](https://www.skyjo.online)). As for the cards added under the avatar and username, I haven't yet pushed this change.

**Comment by Cosmos506** [comment]
Okay I will try locally later thank you

**Comment by Cosmos506** [comment]
I tried everything to go local and I can't do it. I don't know why everything usually works. If everything works for you then it must be good. unfortunately I couldn't see locally if it works sorry I don't understand. 

If it's good you can close the issue. 

 Thanks for your listening and your reaction.
